<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-BS35SKK" failures="2" tests="15" name="testng.NewTest" time="28.388" errors="0" timestamp="2022-10-15T00:11:40 IST" skipped="10">
  <testcase classname="testng.NewTest" name="validLogin" time="7.331"/>
  <system-out/>
  <testcase classname="testng.NewTest" name="testMultipleUserDetials" time="0.927"/>
  <system-out/>
  <testcase classname="testng.NewTest" name="testMultipleUserDetials" time="0.851">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1020)
at testng.NewTest.testMultipleUserDetials(NewTest.java:48)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testMultipleUserDetials -->
  <system-out/>
  <testcase classname="testng.NewTest" name="testMultipleUserDetials" time="1.151">
    <skipped/>
  </testcase> <!-- testMultipleUserDetials -->
  <system-out/>
  <testcase classname="testng.NewTest" name="testMultipleUserDetials" time="1.125"/>
  <system-out/>
  <testcase classname="testng.NewTest" name="testMultipleUserDetials" time="0.879">
    <skipped/>
  </testcase> <!-- testMultipleUserDetials -->
  <system-out/>
  <testcase classname="testng.NewTest" name="testMultipleUserDetials" time="0.921">
    <skipped/>
  </testcase> <!-- testMultipleUserDetials -->
  <system-out/>
  <testcase classname="testng.NewTest" name="testMultipleUserDetials" time="0.957">
    <skipped/>
  </testcase> <!-- testMultipleUserDetials -->
  <system-out/>
  <testcase classname="testng.NewTest" name="testMultipleUserDetials" time="1.577">
    <skipped/>
  </testcase> <!-- testMultipleUserDetials -->
  <system-out/>
  <testcase classname="testng.NewTest" name="testMultipleUserDetials" time="0.913">
    <skipped/>
  </testcase> <!-- testMultipleUserDetials -->
  <system-out/>
  <testcase classname="testng.NewTest" name="testMultipleUserDetials" time="8.072">
    <skipped/>
  </testcase> <!-- testMultipleUserDetials -->
  <system-out/>
  <testcase classname="testng.NewTest" name="testMultipleUserDetials" time="0.881">
    <skipped/>
  </testcase> <!-- testMultipleUserDetials -->
  <system-out/>
  <testcase classname="testng.NewTest" name="testMultipleUserDetials" time="1.025">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1020)
at testng.NewTest.testMultipleUserDetials(NewTest.java:48)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testMultipleUserDetials -->
  <system-out/>
  <testcase classname="testng.NewTest" name="testMultipleUserDetials" time="0.830">
    <skipped/>
  </testcase> <!-- testMultipleUserDetials -->
  <system-out/>
  <testcase classname="testng.NewTest" name="testMultipleUserDetials" time="0.948">
    <skipped/>
  </testcase> <!-- testMultipleUserDetials -->
  <system-out/>
</testsuite> <!-- testng.NewTest -->
